### ISSUE TITLE
localMedia option causes all Cosmicjs sources other than allCosmicjsLocalMedia to disappear from GraphQL

### ISSUE THREAD

**Issue by justinradomski** [cosmicjs/gatsby-source-cosmicjs#19] opened 2020-06-30 22:07 UTC
<img width="318" alt="Screen Shot 2020-06-30 at 5 58 39 PM" src="https://user-images.githubusercontent.com/8386260/86181611-5cd1ce00-bafc-11ea-9cad-edecd3ac0916.png">
<img width="317" alt="Screen Shot 2020-06-30 at 5 59 14 PM" src="https://user-images.githubusercontent.com/8386260/86181612-5cd1ce00-bafc-11ea-92b0-b190b11391e3.png">

The attached screenshots show what happens when enabling localMedia vs leaving disabled. This issue can also be seen on the Gatsby Blog CosmicJS starter here: https://codesandbox.io/s/github/cosmicjs/gatsby-blog-cosmicjs

**Comment by jazibsawar** [comment] 2020-07-02 20:13
@justinradomski I looked at it. But it couldn't able to reproduce. Can you please let me know which version of Node & Gatsby are you using?

**Comment by justinradomski** [comment] 2020-07-02 20:47
@jazibsawar 
Gatsby: 2.23.3
Node: 12.14.0

Were you able to see the issue in the sandbox link for that cosmic blog starter?

**Comment by tonyspiro** [comment] 2020-07-03 16:41
Hey @justinradomski I installed your exact versions and tried and couldn't reproduce the issue as well. Can you tell me more information on what is going in our Slack channel? [Please DM me](https://cosmicslack.herokuapp.com/) and we'll get this sorted out. I'm thinking there may be an issue with your Bucket config or something. I'm closing this for now.

**Comment by tonyspiro** [comment] 2020-07-07 16:05
I'm reopening, because we have found the issue and are working on a fix. The [next version](https://www.npmjs.com/package/gatsby-source-cosmicjs/v/1.2.0-next) includes a temporary fix.

**Comment by jazibsawar** [comment] 2020-07-16 23:29
Hey @justinradomski the issue has been fixed and the latest version has been published on NPM. Be sure to check out the latest version. Thanks

**Closed by jazibsawar** 2020-07-16 23:29 UTC
